
// Objective-C API for talking to the following Go packages
//
//	golang.zx2c4.com/wireguard/apple
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WireGuardKitGo_FRAMEWORK_H__
#define __WireGuardKitGo_FRAMEWORK_H__

#include "Wireguardkitgo.objc.h"
#include "Universe.objc.h"

#endif
