// Objective-C API for talking to golang.zx2c4.com/wireguard/apple Go package.
//   gobind -lang=objc golang.zx2c4.com/wireguard/apple
//
// File is generated by gobind. Do not edit.

#ifndef __Wireguardkitgo_H__
#define __Wireguardkitgo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WireguardkitgoConfig;
@class WireguardkitgoDeviceWrapper;

/**
 * Config — простой экспортируемый тип для примера
 */
@interface WireguardkitgoConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@end

/**
 * DeviceWrapper — экспортируемый тип для управления WireGuard устройством
 */
@interface WireguardkitgoDeviceWrapper : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor DeviceWrapper.NewDeviceWrapper with unsupported parameter or return types

/**
 * Down опускает устройство
 */
- (BOOL)down:(NSError* _Nullable* _Nullable)error;
/**
 * SetPrivateKey устанавливает приватный ключ
 */
- (BOOL)setPrivateKey:(NSString* _Nullable)sk error:(NSError* _Nullable* _Nullable)error;
/**
 * Up поднимает устройство
 */
- (BOOL)up:(NSError* _Nullable* _Nullable)error;
@end

// skipped function NewDeviceWrapper with unsupported parameter or return types


/**
 * SayHello — простая экспортируемая функция для проверки
 */
FOUNDATION_EXPORT NSString* _Nonnull WireguardkitgoSayHello(NSString* _Nullable name);

#endif
